-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-11-23 00:32:49 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- DROP TABLE attendance CASCADE CONSTRAINTS;

-- DROP TABLE classes CASCADE CONSTRAINTS;

-- DROP TABLE coordinators CASCADE CONSTRAINTS;

-- DROP TABLE courses CASCADE CONSTRAINTS;

-- DROP TABLE courses_in_semester CASCADE CONSTRAINTS;

-- DROP TABLE final_grades CASCADE CONSTRAINTS;

-- DROP TABLE grade_categories CASCADE CONSTRAINTS;

-- DROP TABLE grades CASCADE CONSTRAINTS;

-- DROP TABLE groups CASCADE CONSTRAINTS;

-- DROP TABLE lecturers CASCADE CONSTRAINTS;

-- DROP TABLE students_in_classes CASCADE CONSTRAINTS;

-- DROP TABLE users CASCADE CONSTRAINTS;



CREATE TABLE attendance (
            course_code VARCHAR2(5 CHAR) NOT NULL, 
    semester             VARCHAR2(4 CHAR) NOT NULL,
    group_number                             NUMBER(3) NOT NULL,
    attendance_status VARCHAR2(32 CHAR),
    classes_hour      NUMBER(4) NOT NULL,
    classes_day       CHAR(1 BYTE) NOT NULL,
    who_inserted_id    NUMBER(6) NOT NULL,
    user_id     NUMBER(6) NOT NULL
);

CREATE TABLE classes (
        course_code VARCHAR2(5 CHAR) NOT NULL, 
    semester             VARCHAR2(4 CHAR) NOT NULL,
    group_number                             NUMBER(3) NOT NULL,
    type                                            VARCHAR2(16 CHAR) NOT NULL,
    day                                             CHAR(1 BYTE) NOT NULL,
    hour                                            NUMBER(4) NOT NULL,
    length                                          NUMBER(4) NOT NULL,
    "where"                                         VARCHAR2(32 CHAR) NOT NULL

);

ALTER TABLE classes ADD CONSTRAINT classes_pk PRIMARY KEY (course_code, semester, group_number, hour,
                                                            day );

CREATE TABLE coordinators (
    user_id                            NUMBER(6) NOT NULL, 
    course_code VARCHAR2(5 CHAR) NOT NULL,
    semester             VARCHAR2(4 CHAR) NOT NULL
);

ALTER TABLE coordinators
    ADD CONSTRAINT coordinators_pk PRIMARY KEY ( user_id,
                                                 course_code,
                                                 semester );

CREATE TABLE courses (
    course_code VARCHAR2(5 CHAR) NOT NULL,
    title        VARCHAR2(64) NOT NULL
);

ALTER TABLE courses ADD CONSTRAINT courses_pk PRIMARY KEY ( course_code );

CREATE TABLE courses_in_semester (
    course_code VARCHAR2(5 CHAR) NOT NULL,
    semester             VARCHAR2(4 CHAR) NOT NULL
);

ALTER TABLE courses_in_semester ADD CONSTRAINT courses_in_semester_pk PRIMARY KEY ( course_code,
                                                                                    semester );

CREATE TABLE final_grades (
    user_id                            NUMBER(6) NOT NULL, 
    course_code VARCHAR2(5 CHAR) NOT NULL,
    semester             VARCHAR2(4 CHAR) NOT NULL,
    grade                                    NUMBER(3, 2) NOT NULL
);

ALTER TABLE final_grades
    ADD CONSTRAINT final_grades_pk PRIMARY KEY ( user_id,
                                                 grade,
                                                 course_code,
                                                 semester );

CREATE TABLE grade_categories (
    category_id                              NUMBER(10) NOT NULL, 
    course_code VARCHAR2(5 CHAR) NOT NULL,
    semester             VARCHAR2(4 CHAR) NOT NULL,
    description                              VARCHAR2(128 CHAR),
    wage                                     NUMBER(5, 2) NOT NULL
);

ALTER TABLE grade_categories
    ADD CONSTRAINT grade_categories_pk PRIMARY KEY ( category_id,
                                                     course_code,
                                                     semester );

CREATE TABLE grades (
    category_id                              NUMBER(10) NOT NULL, 
    course_code VARCHAR2(5 CHAR) NOT NULL, 
    semester             VARCHAR2(4 CHAR) NOT NULL,
    user_id                                             NUMBER(6) NOT NULL,
    who_inserted_id                                            NUMBER(6) NOT NULL,
    grade                                                     NUMBER(5, 2) NOT NULL,
    "date"                                                    DATE NOT NULL,
    description                                               VARCHAR2(128 CHAR)
);

ALTER TABLE grades
    ADD CONSTRAINT grades_pk PRIMARY KEY ( course_code,
                                           semester,
                                           category_id,
                                           user_id );

CREATE TABLE groups ( 
    course_code VARCHAR2(5 CHAR) NOT NULL,
    semester             VARCHAR2(4 CHAR) NOT NULL,
    group_number                             NUMBER(3) NOT NULL
);

ALTER TABLE groups
    ADD CONSTRAINT groups_pk PRIMARY KEY ( course_code,
                                           semester,
                                           group_number );

CREATE TABLE lecturers (
    user_id                                   NUMBER(6), 
    course_code VARCHAR2(5 CHAR), 
    semester             VARCHAR2(4 CHAR),
    group_number                             NUMBER(3)
);

CREATE TABLE students_in_classes (
    user_id                                   NUMBER(6), 
    course_code VARCHAR2(5 CHAR), 
    semester             VARCHAR2(4 CHAR),
    group_number                             NUMBER(3)
);

CREATE TABLE users (
    user_id  NUMBER(6) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
    name     VARCHAR2(64 CHAR) NOT NULL,
    surname  VARCHAR2(64 CHAR) NOT NULL,
    password VARCHAR2(64 BYTE) NOT NULL,
    mail VARCHAR2(64 BYTE) NOT NULL
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( user_id );
ALTER TABLE users ADD CONSTRAINT mail_const UNIQUE ( mail );
ALTER TABLE attendance ADD CONSTRAINT attendance_pk PRIMARY KEY ( user_id, course_code, semester, group_number, classes_hour,
                                                       classes_day );

ALTER TABLE attendance
    ADD CONSTRAINT attendance_classes_fk FOREIGN KEY ( course_code, semester, group_number, classes_hour,
                                                       classes_day )
        REFERENCES classes (course_code, semester, group_number, hour,
                                                            day );

ALTER TABLE attendance
    ADD CONSTRAINT attendance_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

ALTER TABLE attendance
    ADD CONSTRAINT attendance_users_fkv2 FOREIGN KEY ( who_inserted_id )
        REFERENCES users ( user_id );

ALTER TABLE classes
    ADD CONSTRAINT classes_groups_fk FOREIGN KEY ( course_code,
                                                   semester,
                                                   group_number )
        REFERENCES groups ( course_code,
                            semester,
                            group_number );

ALTER TABLE coordinators
    ADD CONSTRAINT coordinators_cis_fk FOREIGN KEY ( course_code,
                                                                     semester )
        REFERENCES courses_in_semester ( course_code,
                                         semester );

ALTER TABLE coordinators
    ADD CONSTRAINT coordinators_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

ALTER TABLE courses_in_semester
    ADD CONSTRAINT cis_courses_fk FOREIGN KEY ( course_code )
        REFERENCES courses ( course_code );

ALTER TABLE final_grades
    ADD CONSTRAINT final_grades_cis_fk FOREIGN KEY ( course_code,
                                                                     semester )
        REFERENCES courses_in_semester ( course_code,
                                         semester );

ALTER TABLE final_grades
    ADD CONSTRAINT final_grades_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

ALTER TABLE grade_categories
    ADD CONSTRAINT grade_categories_cis_fk FOREIGN KEY ( course_code,
                                                                         semester )
        REFERENCES courses_in_semester ( course_code,
                                         semester );

ALTER TABLE grades
    ADD CONSTRAINT grades_grade_categories_fk FOREIGN KEY ( category_id,
                                                            course_code,
                                                            semester )
        REFERENCES grade_categories ( category_id,
                                      course_code,
                                      semester );

ALTER TABLE grades
    ADD CONSTRAINT grades_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

ALTER TABLE grades
    ADD CONSTRAINT grades_users_fkv2 FOREIGN KEY ( who_inserted_id )
        REFERENCES users ( user_id );

ALTER TABLE groups
    ADD CONSTRAINT groups_courses_in_semester_fk FOREIGN KEY ( course_code,
                                                               semester )
        REFERENCES courses_in_semester ( course_code,
                                         semester );

ALTER TABLE lecturers
    ADD CONSTRAINT lecturers_groups_fk FOREIGN KEY ( course_code,
                                                     semester,
                                                     group_number )
        REFERENCES groups ( course_code,
                            semester,
                            group_number );

ALTER TABLE lecturers
    ADD CONSTRAINT lecturers_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

ALTER TABLE students_in_classes
    ADD CONSTRAINT students_in_classes_groups_fk FOREIGN KEY ( course_code,
                                                               semester,
                                                               group_number )
        REFERENCES groups ( course_code,
                            semester,
                            group_number );

ALTER TABLE students_in_classes
    ADD CONSTRAINT students_in_classes_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );
        
ALTER TABLE students_in_classes
    ADD CONSTRAINT students_in_classes_pk PRIMARY KEY ( user_id, course_code,
                                                               semester,
                                                               group_number );
                                                               
ALTER TABLE lecturers
    ADD CONSTRAINT lecturers_pk PRIMARY KEY ( user_id, course_code,
                                                               semester,
                                                               group_number );

INSERT INTO USERS(name, surname, password, mail)values('q','w','e','rw');