-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-12-07 22:17:19 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

--
-- DROP TABLE attendances CASCADE CONSTRAINTS;
--
-- DROP TABLE classes CASCADE CONSTRAINTS;
--
-- DROP TABLE coordinators CASCADE CONSTRAINTS;
--
-- DROP TABLE courses CASCADE CONSTRAINTS;
--
-- DROP TABLE courses_in_semester CASCADE CONSTRAINTS;
--
-- DROP TABLE final_grades CASCADE CONSTRAINTS;
--
-- DROP TABLE grade_categories CASCADE CONSTRAINTS;
--
-- DROP TABLE grades CASCADE CONSTRAINTS;
--
-- DROP TABLE groups CASCADE CONSTRAINTS;
--
-- DROP TABLE lecturers CASCADE CONSTRAINTS;
--
-- DROP TABLE students_in_groups CASCADE CONSTRAINTS;
--
-- DROP TABLE users CASCADE CONSTRAINTS;


CREATE TABLE attendances (
                             user_id                                          NUMBER(6) NOT NULL,
--  ERROR: Column name length exceeds maximum allowed length(30)
                             course_code VARCHAR2(5 CHAR) NOT NULL,
--  ERROR: Column name length exceeds maximum allowed length(30)
                             semester             VARCHAR2(4 CHAR) NOT NULL,
                             group_number                             NUMBER(3) NOT NULL,
                             class_id_for_group                              NUMBER(3) NOT NULL,
                             "date"                                                  DATE NOT NULL,
                             attendance_status                                       VARCHAR2(32 CHAR) NOT NULL,
                             who_inserted_id                                           NUMBER(6)
);

ALTER TABLE attendances
    ADD CONSTRAINT attendances_pk PRIMARY KEY ( user_id,
                                                course_code,
                                                semester,
                                                group_number,
                                                class_id_for_group,
                                                "date" );

CREATE TABLE classes (
--  ERROR: Column name length exceeds maximum allowed length(30)
                         course_code VARCHAR2(5 CHAR) NOT NULL,
--  ERROR: Column name length exceeds maximum allowed length(30)
                         semester             VARCHAR2(4 CHAR) NOT NULL,
                         group_number                             NUMBER(3) NOT NULL,
                         class_id_for_group                              NUMBER(3) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
                         type                                            VARCHAR2(16 CHAR) NOT NULL,
                         day                                             CHAR(1 CHAR) NOT NULL,
    hour                                            NUMBER(4) NOT NULL,
    length                                          NUMBER(4) NOT NULL,
    "where"                                         VARCHAR2(32 CHAR) NOT NULL
);

ALTER TABLE classes
    ADD CONSTRAINT classes_pk PRIMARY KEY ( class_id_for_group,
                                            group_number,
                                            semester,
                                            course_code );

CREATE TABLE coordinators (
                              user_id                            NUMBER(6) NOT NULL,
--  ERROR: Column name length exceeds maximum allowed length(30)
                              course_code VARCHAR2(5 CHAR) NOT NULL,
                              semester             VARCHAR2(4 CHAR) NOT NULL
);

ALTER TABLE coordinators
    ADD CONSTRAINT coordinators_pk PRIMARY KEY ( user_id,
                                                 course_code,
                                                 semester );

CREATE TABLE courses (
                         course_code VARCHAR2(5 CHAR) NOT NULL,
                         title        VARCHAR2(64 CHAR) NOT NULL
);

ALTER TABLE courses ADD CONSTRAINT courses_pk PRIMARY KEY ( course_code );

CREATE TABLE courses_in_semester (
                                     course_code VARCHAR2(5 CHAR) NOT NULL,
                                     semester             VARCHAR2(4 CHAR) NOT NULL
);

ALTER TABLE courses_in_semester ADD CONSTRAINT courses_in_semester_pk PRIMARY KEY ( course_code,
                                                                                    semester );

CREATE TABLE final_grades (
                              user_id                            NUMBER(6) NOT NULL,
--  ERROR: Column name length exceeds maximum allowed length(30)
                              course_code VARCHAR2(5 CHAR) NOT NULL,
                              semester             VARCHAR2(4 CHAR) NOT NULL,
                              grade                                    NUMBER(3, 2) NOT NULL
);

ALTER TABLE final_grades
    ADD CONSTRAINT final_grades_pk PRIMARY KEY ( user_id,
                                                 course_code,
                                                 semester );

CREATE TABLE grade_categories (
                                  category_id                              NUMBER(6) NOT NULL,
--  ERROR: Column name length exceeds maximum allowed length(30)
                                  course_code VARCHAR2(5 CHAR) NOT NULL,
                                  semester             VARCHAR2(4 CHAR) NOT NULL,
                                  description                              VARCHAR2(128 CHAR),
                                  wage                                     NUMBER(5, 2) NOT NULL
);

ALTER TABLE grade_categories
    ADD CONSTRAINT grade_categories_pk PRIMARY KEY ( category_id,
                                                     course_code,
                                                     semester );

CREATE TABLE grades (
                        category_id                              NUMBER(6) NOT NULL,
--  ERROR: Column name length exceeds maximum allowed length(30)
                        course_code VARCHAR2(5 CHAR) NOT NULL,
--  ERROR: Column name length exceeds maximum allowed length(30)
                        semester             VARCHAR2(4 CHAR) NOT NULL,
                        user_id                                             NUMBER(6) NOT NULL,
                        who_inserted_id                                            NUMBER(6),
                        grade                                                     NUMBER(5, 2) NOT NULL,
                        "date"                                                    DATE NOT NULL,
                        description                                               VARCHAR2(128 CHAR)
);

ALTER TABLE grades
    ADD CONSTRAINT grades_pk PRIMARY KEY ( course_code,
                                           semester,
                                           category_id,
                                           user_id );

CREATE TABLE groups (
--  ERROR: Column name length exceeds maximum allowed length(30)
                        course_code VARCHAR2(5 CHAR) NOT NULL,
                        semester             VARCHAR2(4 CHAR) NOT NULL,
                        group_number                             NUMBER(3) NOT NULL
);

ALTER TABLE groups
    ADD CONSTRAINT groups_pk PRIMARY KEY ( course_code,
                                           semester,
                                           group_number );

CREATE TABLE lecturers (
                           user_id                                   NUMBER(6) NOT NULL,
--  ERROR: Column name length exceeds maximum allowed length(30)
                           course_code VARCHAR2(5 CHAR) NOT NULL,
--  ERROR: Column name length exceeds maximum allowed length(30)
                           semester             VARCHAR2(4 CHAR) NOT NULL,
                           group_number                             NUMBER(3) NOT NULL
);

ALTER TABLE lecturers
    ADD CONSTRAINT lecturers_pk PRIMARY KEY ( user_id,
                                              course_code,
                                              semester,
                                              group_number );

CREATE TABLE students_in_groups (
                                     user_id                                   NUMBER(6) NOT NULL,
--  ERROR: Column name length exceeds maximum allowed length(30)
                                     course_code VARCHAR2(5 CHAR) NOT NULL,
--  ERROR: Column name length exceeds maximum allowed length(30)
                                     semester             VARCHAR2(4 CHAR) NOT NULL,
                                     group_number                             NUMBER(3) NOT NULL
);

ALTER TABLE students_in_groups
    ADD CONSTRAINT students_in_groups_pk PRIMARY KEY ( user_id,
                                                        course_code,
                                                        semester,
                                                        group_number );

CREATE TABLE users (
                       user_id  NUMBER(6) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
                       name     VARCHAR2(64 CHAR) NOT NULL,
                       surname  VARCHAR2(64 CHAR) NOT NULL,
                       password VARCHAR2(64 CHAR) NOT NULL,
                       mail VARCHAR2(64 CHAR) NOT NULL,
                       status   VARCHAR2(64 CHAR) NOT NULL
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( user_id );

ALTER TABLE attendances
    ADD CONSTRAINT attendances_classes_fk FOREIGN KEY ( class_id_for_group,
                                                        group_number,
                                                        semester,
                                                        course_code )
        REFERENCES classes ( class_id_for_group,
                             group_number,
                             semester,
                             course_code );

ALTER TABLE attendances
    ADD CONSTRAINT attendances_users_fk FOREIGN KEY ( who_inserted_id )
        REFERENCES users ( user_id );

ALTER TABLE attendances
    ADD CONSTRAINT attendances_users_fkv2 FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

ALTER TABLE classes
    ADD CONSTRAINT classes_groups_fk FOREIGN KEY ( course_code,
                                                   semester,
                                                   group_number )
        REFERENCES groups ( course_code,
                            semester,
                            group_number );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE coordinators
    ADD CONSTRAINT coordinators_courses_in_semester_fk FOREIGN KEY ( course_code,
                                                                     semester )
        REFERENCES courses_in_semester ( course_code,
                                         semester );

ALTER TABLE coordinators
    ADD CONSTRAINT coordinators_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

ALTER TABLE courses_in_semester
    ADD CONSTRAINT courses_in_semester_courses_fk FOREIGN KEY ( course_code )
        REFERENCES courses ( course_code );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE final_grades
    ADD CONSTRAINT final_grades_courses_in_semester_fk FOREIGN KEY ( course_code,
                                                                     semester )
        REFERENCES courses_in_semester ( course_code,
                                         semester );

ALTER TABLE final_grades
    ADD CONSTRAINT final_grades_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE grade_categories
    ADD CONSTRAINT grade_categories_courses_in_semester_fk FOREIGN KEY ( course_code,
                                                                         semester )
        REFERENCES courses_in_semester ( course_code,
                                         semester );

ALTER TABLE grades
    ADD CONSTRAINT grades_grade_categories_fk FOREIGN KEY ( category_id,
                                                            course_code,
                                                            semester )
        REFERENCES grade_categories ( category_id,
                                      course_code,
                                      semester );

ALTER TABLE grades
    ADD CONSTRAINT grades_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

ALTER TABLE grades
    ADD CONSTRAINT grades_users_fkv2 FOREIGN KEY ( who_inserted_id )
        REFERENCES users ( user_id );

ALTER TABLE groups
    ADD CONSTRAINT groups_courses_in_semester_fk FOREIGN KEY ( course_code,
                                                               semester )
        REFERENCES courses_in_semester ( course_code,
                                         semester );

ALTER TABLE lecturers
    ADD CONSTRAINT lecturers_groups_fk FOREIGN KEY ( course_code,
                                                     semester,
                                                     group_number )
        REFERENCES groups ( course_code,
                            semester,
                            group_number );

ALTER TABLE lecturers
    ADD CONSTRAINT lecturers_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

ALTER TABLE students_in_groups
    ADD CONSTRAINT students_in_groups_groups_fk FOREIGN KEY ( course_code,
                                                               semester,
                                                               group_number )
        REFERENCES groups ( course_code,
                            semester,
                            group_number );

ALTER TABLE students_in_groups
    ADD CONSTRAINT students_in_groups_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );
ALTER TABLE users ADD CONSTRAINT mail_const UNIQUE ( mail );

